### PR TITLE
fix(Tracking): cache tracker source when OnEnable - fixes #486

### LINKED ISSUE #486: Component Tracker Proxy does not cache the proxy source
version 21870267bd43c83fb05ed002ee18d55cfbb0d117

1. Create a game object and add ComponentTrackerProxy
2. Fill in its ProxySource with LeftControllerAlias
3. Change inspector to Debug mode and then Play

### Issue

Its CachedVelocityTracker is none. thus the component doesn't work

### Expected Behaviour

Its CachedVelocityTracker should be filled in with the velocity tracker on LeftControllerAlias.

### PR DESCRIPTION
**Pull request by fight4dream**
This fix will cache velocity tracker for this component to work
when the ProxySource is set up in editor time.

### CODE REVIEW

**Comment by fight4dream** [comment]
fixes #486

File: Runtime/Tracking/Velocity/ComponentTrackerProxy.cs [hunk 1]
```diff
@@ -46,6 +51,14 @@ protected override Vector3 DoGetAngularVelocity()
         /// </summary>
         [CalledAfterChangeOf(nameof(ProxySource))]
         protected virtual void OnAfterProxySourceChange()
+        {
+            SetCachedVelocityTracker();
+        }
+
+        /// <summary>
+        /// Sets the VelocityTracker cache to the first found <see ref="VelocityTracker"> on the <see ref="ProxySource"> or any of its descendants.
```
Comment (bddckr) [inline Runtime/Tracking/Velocity/ComponentTrackerProxy.cs]:
```suggestion
        /// Sets <see ref="cachedVelocityTracker"> to the first found <see ref="VelocityTracker"> on the <see ref="ProxySource"> or any of its descendants.
```

File: Runtime/Tracking/Velocity/ComponentTrackerProxy.cs [hunk 2]
```diff
@@ -46,6 +51,14 @@ protected override Vector3 DoGetAngularVelocity()
...
+        {
+            SetCachedVelocityTracker();
+        }
+
+        /// <summary>
+        /// Sets the VelocityTracker cache to the first found <see ref="VelocityTracker"> on the <see ref="ProxySource"> or any of its descendants.
+        /// </summary>
+        protected virtual void SetCachedVelocityTracker()
         {
             cachedVelocityTracker = ProxySource == null ? null : ProxySource.GetComponentInChildren<VelocityTracker>();
```
Comment (bddckr) [inline Runtime/Tracking/Velocity/ComponentTrackerProxy.cs]: We have a nice extension method for this:
```suggestion
            cachedVelocityTracker = ProxySource.TryGetComponent<VelocityTracker>(true);
```

File: Runtime/Tracking/Velocity/ComponentTrackerProxy.cs (hunk 1 above)
Comment (fight4dream) [reply Runtime/Tracking/Velocity/ComponentTrackerProxy.cs]: done in new commit

File: Runtime/Tracking/Velocity/ComponentTrackerProxy.cs (hunk 2 above)
Comment (fight4dream) [reply Runtime/Tracking/Velocity/ComponentTrackerProxy.cs]: done in new commit
